name: lerobot
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.12.1=h7934f7d_0
  - arrow=1.4.0=pyhcf101f3_0
  - binaryornot=0.4.4=pyhd8ed1ab_2
  - binutils_impl_linux-64=2.39=he00db2b_1
  - binutils_linux-64=2.39=h5fc0e48_13
  - brotli-python=1.2.0=py310h8cfb67f_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - chardet=5.2.0=pyhd8ed1ab_3
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.0=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - cookiecutter=2.6.0=pyhd8ed1ab_1
  - dav1d=1.2.1=h5eee18b_0
  - egl-probe=1.0.2=py310hea6c23e_4
  - expat=2.7.1=hecca717_0
  - ffmpeg=6.1.1=hecf7045_5
  - fontconfig=2.15.0=h7e30c49_1
  - freetype=2.13.3=h4a9f257_0
  - gcc=9.5.0=h1fea6ba_13
  - gcc_impl_linux-64=9.5.0=h99780fb_19
  - gcc_linux-64=9.5.0=h4258300_13
  - gettext=0.21.0=hedfda30_2
  - giflib=5.2.2=h5eee18b_0
  - glew=2.2.0=h3abd4de_0
  - graphite2=1.3.14=h295c915_1
  - gxx_impl_linux-64=9.5.0=h99780fb_19
  - gxx_linux-64=9.5.0=h43f449f_13
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=10.2.0=hdfddeaa_1
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.1=h6a678d5_0
  - idna=3.11=pyhd8ed1ab_0
  - jansson=2.14=h5eee18b_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jpeg=9f=h5ce9db8_0
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.39=hcc3a1bd_1
  - leptonica=1.82.0=hfdeec58_3
  - lerc=4.0.0=h6a678d5_0
  - libarchive=3.8.2=h3ec8f01_0
  - libblas=3.9.0=38_h4a7cf45_openblas
  - libcblas=3.9.0=38_h0358290_openblas
  - libcurl=8.16.0=heebcbe5_0
  - libdeflate=1.22=h5eee18b_0
  - libdrm=2.4.125=hb03c661_1
  - libegl=1.7.0=ha4b6fd6_2
  - libegl-devel=1.7.0=ha4b6fd6_2
  - libev=4.33=h7f8727e_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-devel_linux-64=9.5.0=h0a57e50_19
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgl=1.7.0=ha4b6fd6_2
  - libgl-devel=1.7.0=ha4b6fd6_2
  - libglib=2.84.4=h77a78f3_0
  - libglu=9.0.3=h5888daf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libglx-devel=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.8=hf80d704_0
  - liblapack=3.9.0=38_h47877c9_openblas
  - libllvm20=20.1.8=hecd9e04_0
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.1=h697f920_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libogg=1.3.5=h27cfd23_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libopengl=1.7.0=ha4b6fd6_2
  - libopenjpeg=2.5.4=hee96239_1
  - libopus=1.3.1=h5eee18b_1
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h2ed474d_0
  - libsanitizer=9.5.0=h2f262e1_19
  - libsqlite=3.51.0=h0c1763c_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-devel_linux-64=9.5.0=h0a57e50_19
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtheora=1.2.0=h32ad74f_1
  - libtiff=4.7.0=hde9077f_0
  - libunistring=1.3=hb25bd0a_0
  - libuuid=2.41.2=he9a06e4_0
  - libuv=1.48.0=h5eee18b_0
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.15.2=h4cb591d_0
  - libwebp=1.3.2=h9f374a3_1
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - make=4.4.1=hb9d3cd8_2
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py310h3406613_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mesa=2.1.1=pyhd8ed1ab_0
  - mesalib=25.0.5=h57bcd07_2
  - ncurses=6.5=h2d0b736_3
  - networkx=3.4.2=pyh267e887_2
  - numpy=2.2.6=py310hefbff90_0
  - openh264=2.6.0=he621ea3_0
  - openjpeg=2.5.4=h4e0627c_1
  - openssl=3.6.0=h26f9b46_0
  - pandas=2.3.3=py310h0158d43_1
  - pcre2=10.46=hf426167_0
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - pixman-cos7-x86_64=0.34.0=ha675448_1106
  - pthread-stubs=0.3=h0ce48e5_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.19=h3c07f61_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-slugify=8.0.4=pyhd8ed1ab_1
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py310h3406613_0
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rhash=1.4.6=ha914fed_0
  - rich=14.2.0=pyhcf101f3_0
  - setuptools=80.9.0=py310h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - spirv-tools=2025.4=hb700be7_0
  - sqlite=3.51.0=h2a70700_0
  - sysroot_linux-64=2.17=h0157908_18
  - tesseract=5.2.0=hb0d2e87_3
  - text-unidecode=1.3=pyhd8ed1ab_2
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.2=py310h7c4b9e2_2
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxshmfence=1.3.3=hb9d3cd8_0
  - xorg-x11-server-common-cos7-x86_64=1.20.4=ha675448_1106
  - xorg-x11-server-xvfb-cos7-x86_64=1.20.4=ha675448_1106
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h280c20c_3
  - zlib=1.3.1=hb25bd0a_0
  - zstandard=0.25.0=py310h139afa4_1
  - zstd=1.5.7=h11fc155_0
  - pip:
      - absl-py==2.3.1
      - accelerate==1.11.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - av==15.1.0
      - bddl==1.0.1
      - cffi==2.0.0
      - cloudpickle==3.1.2
      - cmake==4.1.2
      - cmeel==0.57.3
      - cmeel-assimp==5.4.3.1
      - cmeel-boost==1.87.0.1
      - cmeel-console-bridge==1.0.2.3
      - cmeel-octomap==1.10.0
      - cmeel-qhull==8.0.2.1
      - cmeel-tinyxml2==10.0.0
      - cmeel-urdfdom==4.0.1
      - cmeel-zlib==1.3.1
      - coal-library==3.0.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==4.1.1
      - decorator==5.2.1
      - deepdiff==8.6.1
      - diffusers==0.35.2
      - dill==0.4.0
      - dm-control==1.0.34
      - dm-env==1.6
      - dm-tree==0.1.9
      - draccus==0.10.0
      - easydict==1.13
      - eigenpy==3.10.3
      - einops==0.8.1
      - eiquadprog==1.2.9
      - etils==1.13.0
      - evdev==1.9.2
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - farama-notifications==0.0.4
      - fastjsonschema==2.21.2
      - feetech-servo-sdk==1.0.0
      - filelock==3.20.0
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - future==1.0.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - glfw==2.10.0
      - grpcio==1.73.1
      - gym-aloha==0.1.3
      - gym-hil==0.1.13
      - gym-pusht==0.1.6
      - gymnasium==1.2.2
      - h5py==3.15.1
      - hf-egl-probe==1.0.2
      - hf-libero==0.1.3
      - hf-transfer==0.1.9
      - hf-xet==1.2.0
      - hidapi==0.14.0.post4
      - huggingface-hub==0.35.3
      - hydra-core==1.3.2
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - iniconfig==2.3.0
      - inquirerpy==0.3.4
      - ipython==8.37.0
      - ischedule==1.2.7
      - jedi==0.19.2
      - jsonlines==4.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-core==5.9.1
      - jupytext==1.18.1
      - kiwisolver==1.4.9
      - labmaze==1.0.6
      - lazy-loader==0.4
      - lerobot==0.4.1
      - llvmlite==0.45.1
      - lxml==6.0.2
      - markdown==3.10
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - mdit-py-plugins==0.5.0
      - mergedeep==1.3.4
      - meshcat==0.3.2
      - mpmath==1.3.0
      - mujoco==3.3.2
      - multidict==6.7.0
      - multiprocess==0.70.16
      - mypy-extensions==1.1.0
      - nbformat==5.10.4
      - numba==0.62.1
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - omegaconf==2.3.0
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - orderly-set==5.5.0
      - packaging==25.0
      - parso==0.8.5
      - pexpect==4.9.0
      - pfzy==0.3.4
      - pillow==12.0.0
      - pin==3.4.0
      - placo==0.9.16
      - platformdirs==4.5.0
      - pluggy==1.6.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==6.31.0
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==22.0.0
      - pycparser==2.23
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pygame==2.6.1
      - pymunk==6.11.1
      - pyngrok==7.4.1
      - pynput==1.8.1
      - pyopengl==3.1.10
      - pyopengl-accelerate==3.1.10
      - pyparsing==3.2.5
      - pyserial==3.5
      - pytest==9.0.1
      - python-xlib==0.33
      - pyyaml-include==1.4.1
      - pyzmq==27.1.0
      - referencing==0.37.0
      - regex==2025.11.3
      - rerun-sdk==0.26.2
      - rhoban-cmeel-jsoncpp==1.9.4.9
      - robomimic==0.2.0
      - robosuite==1.4.0
      - rpds-py==0.28.0
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - scipy==1.15.3
      - sentry-sdk==2.44.0
      - shapely==2.1.2
      - smmap==5.0.2
      - stack-data==0.6.3
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - termcolor==3.2.0
      - thop==0.1.1-2209072238
      - tifffile==2025.5.10
      - tokenizers==0.22.1
      - toml==0.10.2
      - tomli==2.3.0
      - torch==2.7.1
      - torchcodec==0.5
      - torchvision==0.22.1
      - traitlets==5.14.3
      - transformers==4.57.1
      - triton==3.3.1
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - u-msgpack-python==2.8.0
      - uv==0.9.9
      - wandb==0.21.4
      - wcwidth==0.2.14
      - werkzeug==3.1.3
      - wrapt==2.0.1
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
variables:
  MUJOCO_GL: egl
  PYOPENGL_PLATFORM: egl
  CPATH: /home1/ssl7/miniforge3/envs/lerobot/include
  LD_LIBRARY_PATH: 
    /home1/ssl7/miniforge3/envs/lerobot/lib:/home1/ssl7/.mujoco/mujoco210/bin
prefix: /home1/ssl7/miniforge3/envs/lerobot
